version: '2'
services:
  nginx:
    build: ./nginx/
    restart: always
    ports:
      - 80:80
      - 443:443
    network_mode: host
    volumes:
      - nginx_dehydrated:/etc/dehydrated/

volumes:
  nginx_dehydrated:
